name: service_registry

description: A Service registry for dart. It is a simple attempt to provide some sort of IoC in a dart environment, it makes much easier to test components that rely on external services, because we can easily mock then and add to the registry

version: 2.0.0

author: Rafael Roman <panthro.rafael@gmail.com>

homepage: https://github.com/panthro/ServiceRegistry

environment:
  sdk: ">=1.23.0 <3.0.0"

dev_dependencies:
  test: ^1.3.0
  coverage: "^0.12.2"
#  dart_codecov_generator: "^0.4.0"