name: service_registry

description: A Service registry for dart.

version: 1.0.1

author: Rafael Roman <panthro.rafael@gmail.com>

homepage: https://github.com/panthro/ServiceRegistry

environment:
  sdk: ">=1.23.0 <2.0.0"

dev_dependencies:
  test: ^0.12.0
  coverage: "^0.7.0"
  dart_codecov_generator: "^0.4.0"